<?php
/**
 * @file
 * 
 * 
 *
 * @author Kálmán Hosszu - hosszu.kalman@gmail.com - http://premiumcmsthemes.com http://www.kalman-hosszu.com
 */
 
/* ====================== */
/* ==== DRUPAL HOOKS ==== */
/* ====================== */

/**
 * Implementation of hook_menu().
 *
 * @return An array of menu items.
 */
function multiform_test_menu() {
  $items = array();

  $items['multiform-test/1'] = array(
    'title' => 'Multiform test page 1',
    'page callback' => 'multiform_get_form',
    'page arguments' => array(array('multiform_test1_1'), array('multiform_test1_2')),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}


/* ====================== */
/* == MODULE FUNCTIONS == */
/* ====================== */